import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

self.skipWaiting()
clientsClaim()

cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// -----------------------------------------------------------------------------
// PUSH NOTIFICATION HANDLER
// -----------------------------------------------------------------------------
self.addEventListener('push', (event) => {
    const data = event.data?.json() ?? { title: 'New Message', body: 'You have a new message' }

    const options = {
        body: data.body,
        icon: '/pwa-192x192.png', // Ensure this path matches your public folder
        badge: '/pwa-192x192.png',
        data: {
            url: data.url || '/chat', // Deep link URL
            channel: data.channel
        },
        vibrate: [200, 100, 200],
        requireInteraction: true // Keep notification visible until user interacts
    }

    event.waitUntil(
        self.registration.showNotification(data.title, options)
    )
})

// -----------------------------------------------------------------------------
// NOTIFICATION CLICK HANDLER
// -----------------------------------------------------------------------------
self.addEventListener('notificationclick', (event) => {
    event.notification.close()

    const targetUrl = new URL(event.notification.data.url, self.location.origin).href

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            // 1. Try to find an existing open window
            for (const client of clientList) {
                if (client.url === targetUrl && 'focus' in client) {
                    return client.focus()
                }
                // If exact match fails, just focus any open app window and navigate
                if ('focus' in client) {
                    client.focus();
                    return client.navigate(targetUrl);
                }
            }

            // 2. If no window is open, open a new one
            if (self.clients.openWindow) {
                return self.clients.openWindow(targetUrl)
            }
        })
    )
})
